[package]
name = "uniject"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_System_ProcessStatus", "Win32_System_Threading", "Win32_System_Memory", "Win32_System_Diagnostics_Debug", "Win32_System_Diagnostics_ToolHelp", "Win32_Security"] }
iced-x86 = { version = "1", default-features= false, features = ["code_asm", "no_std"] }
